apiVersion: apps/v1
kind: Deployment
metadata: 
  name: grpc-productinfo-server
spec: 
  replicas: 1
  selector: 
    matchLabels:
      app: grpc-productinfo-server
  template: 
    metadata:
      labels:
        app: grpc-productinfo-server
    spec:
      containers:
      - name: grpc-productinfo-server
        image: jazzsaxmafia/grpc-productinfo-server
        ports: 
        - containerPort: 50051
          name: grpc

